defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: mongo_on_rails_blog_development

test:
  <<: *defaults
  database: mongo_on_rails_blog_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
